import {
  bugIcon as bug,
  darkIcon as dark,
  dragonIcon as dragon,
  fairyIcon as fairy,
  normalIcon as normal,
  electricIcon as electric,
  fightingIcon as fighting,
  fireIcon as fire,
  flyingIcon as flying,
  ghostIcon as ghost,
  grassIcon as grass,
  groundIcon as ground,
  iceIcon as ice,
  poisonIcon as poison,
  psychicIcon as psychic,
  rockIcon as rock,
  steelIcon as steel,
  waterIcon as water,
} from "../svg/icons";

export const typeList = [
  bug,
  dark,
  dragon,
  normal,
  fairy,
  electric,
  fighting,
  fire,
  flying,
  ghost,
  grass,
  ground,
  ice,
  poison,
  psychic,
  rock,
  steel,
  water,
];
